# filepath: /workspaces/coverage_badge/.github/workflows/coverage.yml
name: Python Test Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r my-python-app/requirements.txt

    - name: Run tests with coverage
      run: |
        pytest --cov=src my-python-app/tests/

    - name: Generate coverage badge
      run: |
        coverage-badge -o my-python-app/coverage.svg -f

    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true