name: Test and Generate Coverage Badge

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov coverage-badge

    - name: Run tests and generate coverage reports
      run: |
        pytest --cov=src --cov-report=html --cov-report=json my-python-app/tests/
        coverage-badge -o coverage.svg

    - name: Deploy badge to gh-pages
      run: |
        # Configure Git
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
    
        # Create or switch to gh-pages branch
        git checkout --orphan gh-pages
    
    
        # Copy or move the generated badge
        mv coverage.svg index.html
    
        # Add and commit only index.html
        git add index.html
        git commit -m "GitHub Actions: Deploy test coverage badge for commit $GITHUB_SHA to gh-pages branch"

        # Clean up all files to ensure only the badge is included
        git reset --hard
        git clean -fdx
    
        # Force push the gh-pages branch
        git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages
      
