name: Test and Generate Coverage Badge

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov coverage-badge

    - name: Run tests and generate coverage reports
      run: |
        pytest --cov=src --cov-report=html --cov-report=json my-python-app/tests/
        coverage-badge -o coverage.svg
        pwd

    - name: Deploy badge to gh-pages
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git checkout --orphan gh-pages
        git reset --hard
        git clean -fdx
        pwd
        mv ../coverage.svg index.html  # move the badge before cleaning
        git add .
        git commit -m "GitHub Actions: Deploy test coverage badge for commit $GITHUB_SHA to gh-pages branch"
        git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages